### ISSUE TITLE
exception=TypeError("'<' not supported between instances of 'int' and 'str'")>

### ISSUE THREAD

**Issue by ketsapiwiq** [e-p-armstrong/augmentoolkit#20]
Hi! I have trouble debugging this. It's probably something sent back by the API with a `<`?
Thanks in advance.
```py
./output/qatuples_revised/revised_20.json
Loaded file:
[
    "How?",
    "How.",
    "./raw_txt_input/01_02"
]
-------------- QUESTIONS REVISED ------------- STATS SO FAR:
Nones: 0
Non-nones: 44
Total: 44
---------------- ONTO EXAMPLES GENERATION-------------------
  0%|          | 0/11 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/hadrien/git/augmentoolkit/processing.py", line 443, in <module>
    asyncio.run(main())
  File "/home/hadrien/.pyenv/versions/3.11.9/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/hadrien/.pyenv/versions/3.11.9/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hadrien/.pyenv/versions/3.11.9/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/hadrien/git/augmentoolkit/processing.py", line 364, in main
    await future
  File "/home/hadrien/.pyenv/versions/3.11.9/lib/python3.11/asyncio/tasks.py", line 615, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/home/hadrien/git/augmentoolkit/processing.py", line 107, in run_task_with_limit
    return await task
           ^^^^^^^^^^
  File "/home/hadrien/git/augmentoolkit/augmentoolkit/control_flow_functions/control_flow_functions.py", line 1859, in create_info
    sample_size = min(rearrangements_to_take, len(all_permutations))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'int' and 'str'
2024-05-26 12:17:10,111 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-72' coro=<main.<locals>.run_task_with_limit() done, defined at /home/hadrien/git/augmentoolkit/processing.py:104> exception=TypeError("'<' not supported between instances of 'int' and 'str'")>
Traceback (most recent call last):
  File "/home/hadrien/git/augmentoolkit/processing.py", line 107, in run_task_with_limit
    return await task
           ^^^^^^^^^^
  File "/home/hadrien/git/augmentoolkit/augmentoolkit/control_flow_functions/control_flow_functions.py", line 1859, in create_info
    sample_size = min(rearrangements_to_take, len(all_permutations))
```

**Comment by e-p-armstrong** [comment]
hmm,  that's strange. Are you able to share your config and input texts?

**Comment by ketsapiwiq** [comment]
Important point, I was trying out a weird openAI endpoint (Mistral), so maybe this is the cause. I'll retry next week and will try to dig deeper.

**Comment by e-p-armstrong** [comment]
PR has been merged that allegedly fixes this

**Comment by AllyourBaseBelongToUs** [comment]
Im sorry for reviving an old issue.

This error is an error when typing new values in the gradio UI

its being written into the config file with '' 

example:

you type 30 in max concurrency, in the config file it appears as '30' which causes this error

**Comment by Katehuuh** [comment]
> PR has been merged that allegedly fixes this

same here. `streamlit run .\streamlit_app.py`

```cmd
SCRAPING IS ON. BEGINNING GUTENBERG SCRAPE! This will modify your input folder.
Traceback (most recent call last):
  File "C:\augmentoolkit\original\processing.py", line 436, in <module>
    asyncio.run(main())
  File "C:\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\augmentoolkit\original\processing.py", line 127, in main
    steps.scrape_text_using_config(start_url=START_URL, max_books=MAX_BOOKS, max_failures=MAX_FAILURES)
  File "C:\augmentoolkit\original\steps.py", line 1433, in scrape_text_using_config
    while books_downloaded < max_books and consecutive_failures < max_failures:
TypeError: '<' not supported between instances of 'int' and 'str'
```
