### ISSUE TITLE
IndexError: list out of range

### ISSUE THREAD

**Issue by BovineOverlord** [e-p-armstrong/augmentoolkit#30]
When running python processing.py, I am met with this error;

Traceback (most recent call last):
  File "D:\AI\LLM\augmentoolkit-master\processing.py", line 422, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\AI\LLM\augmentoolkit-master\processing.py", line 165, in main
    paragraphs_processed[0]
IndexError: list index out of range

I think it is saying there is an issue with the input file, however it is in the correct directory and in .txt format. I've troubleshooted and cannot find an issue on my end.

**Comment by e-p-armstrong** [comment]
Found a problem where the default config's not directory was "raw_text_input" not "raw_txt_input", this should fix your problem, try pulling and running again?

**Comment by BovineOverlord** [comment]
Yes, that fixed it, thank you. A different error came up- I'll create a separate thread for it.
