### ISSUE TITLE
ERROR WHILE RUNNING RUN_AUGMENTOOLKIT FILE

### ISSUE THREAD

**Issue by MuhammadBilal848** [e-p-armstrong/augmentoolkit#79]
Hi, im trying to run `run_augmentoolkit.py` but getting this error:

```
Response:
-----

No response to print
2024-11-21 14:31:57,173 - ERROR - Above prompt resulted in error, probably the model's fault: Error code: 401 - {'detail': 'User is not authorized to access this resource'}
Traceback (most recent call last):
  File "/home/bilal/Downloads/augmentoolkit/augmentoolkit/generation_functions/generation_step_class.py", line 142, in generate
    response, timeout = await self.engine_wrapper.submit_chat(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bilal/Downloads/augmentoolkit/augmentoolkit/generation_functions/engine_wrapper_class.py", line 113, in submit_chat
    stream = await self.client.chat.completions.create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bilal/anaconda3/envs/augtk/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1661, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/home/bilal/anaconda3/envs/augtk/lib/python3.11/site-packages/openai/_base_client.py", line 1839, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bilal/anaconda3/envs/augtk/lib/python3.11/site-packages/openai/_base_client.py", line 1533, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/bilal/anaconda3/envs/augtk/lib/python3.11/site-packages/openai/_base_client.py", line 1634, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'detail': 'User is not authorized to access this resource'}
Generation step failed -- too many retries!
Traceback (most recent call last):
  File "/home/bilal/Downloads/augmentoolkit/augmentoolkit/generation_functions/pipeline_step_class.py", line 89, in generate_data
    result, full_output = await generator.generate(**processed_data, **self.static_arguments)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bilal/Downloads/augmentoolkit/augmentoolkit/generation_functions/generation_step_class.py", line 181, in generate
    raise Exception("Generation step failed -- too many retries!")
Exception: Generation step failed -- too many retries!
cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/home/bilal/Downloads/augmentoolkit/augmentoolkit/generation_functions/pipeline_step_class.py", line 133, in run
    result, full_output = await self.generate_data(processed_data, engine_wrapper)
    ^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
100%|███████████████████████████████████████████| 20/20 [00:05<00:00,  3.89it/s]
Converting generations to training data
entering saving mode
Converting ./output/judge_paragraph_generations/intermediate_generations to a dataset
Traceback (most recent call last):
  File "/home/bilal/Downloads/augmentoolkit/original/processing.py", line 436, in <module>
    asyncio.run(main())
  File "/home/bilal/anaconda3/envs/augtk/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/bilal/anaconda3/envs/augtk/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bilal/anaconda3/envs/augtk/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/bilal/Downloads/augmentoolkit/original/processing.py", line 270, in main
    steps.convert_logging_to_dataset(input_pth=os.path.join("judge_paragraph_generations", "intermediate_generations"), output_pth="judge_paragraph_generations")
  File "/home/bilal/Downloads/augmentoolkit/original/steps.py", line 96, in convert_logging_to_dataset
    raise Exception("ERROR!! Trying to convert a logging directory to a dataset, when that directory does not exist!")
Exception: ERROR!! Trying to convert a logging directory to a dataset, when that directory does not exist!
```

Configurations:

```
API:
  LARGE_MODEL: meta-llama/Meta-Llama-3.1-8B-Instruct-Reference
  LARGE_API_KEY: MY_HIDDEN_API
  LARGE_BASE_URL: https://api.together.xyz 
  LARGE_MODE: api
  SMALL_MODEL: meta-llama/Meta-Llama-3.1-8B-Instruct
  SMALL_BASE_URL: https://api.deepinfra.com/v1/openai
  SMALL_API_KEY: key-here
  SMALL_MODE: api
HUGGINGFACE:
  HUB_PATH: yourusername/your-path-here
  PRIVATE: False
  PUSH_TO_HUB: False
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./input
  OUTPUT: ./output
  PROMPTS: ./prompts
PHASE:
  PHASE_INDEX: 3
  WORK_IN_PHASES: False
SKIP:
  ANSWER_RELEVANCY_CHECK: False
  REPAIR_QA_TUPLES: False
  FILTER_CHUNKS: False
  QUESTION_CHECK: False
  CONVERSATION_GENERATION: False
SYSTEM:
  CHUNK_SIZE: 1900
  COMPLETION_MODE: False
  CONCURRENCY_LIMIT: 50
  CONVERSATION_INSTRUCTIONS: For this conversation, you are generating a chat between
    a generalist, generic AI assistant, and a human.
  DOUBLE_CHECK_COUNTER: 1
  DO_NOT_USE_SYSTEM_PROMPTS: False
  FINAL_ASSISTANT_PROMPTS_NO_RAG: [
  'You are a helpful AI assistant.',
  'You are A VASTLY intelligent ARTIFICIAL INTELLIGENCE with DOMAIN-EXPERT KNOWLEDGE from a variety of fields.
  
  USE your knowledge to be helpful and truthfully answer questions about the world.',
  "u are ai asstant plz answr questions"] # a wide variety of system prompts helps the AI learn better. What, you expect your users to spell things right?
  FINAL_ASSISTANT_PROMPTS_RAG: [
  'You are a helpful AI assistant. Some knowledge:
  
  {data}',
  
  '{data}
  
  You are an AI domain expert. Answer questions',
  'You are an AI with vast knowledge. Here is some potentially-relevant context:
  
  {data}

  Answer questions according to your knowledge.']
  STOP: True
  SUBSET_SIZE: 20
  USE_FILENAMES: False
  USE_SUBSET: True
  RAG_FAILURE_PERCENTAGE: 0.1 # How much of the RAG data has the wrong chunk retrieved deliberately? To train it to answer correctly even if wrong facts are shown to it. We will need another dataset thing for making data where the question asks something that is not present and the rag retrieves something irrelevant obbviously and it is supposed to say "I don't know" or something.
SCRAPING:
  USE_GUTENBERG: False
  START_URL: "https://www.gutenberg.org/ebooks/bookshelf/57"
  MAX_BOOKS: 5
  MAX_FAILURES: 5
```

P.S: The idea is good but the repo needs maintainers as it takes a lot of time to get answers. Thanks

**Comment by e-p-armstrong** [comment]
Check the traceback, you're getting a 401. This seems to be because you have set the api key and model for the large model, but not the small one (which is still using deepinfra defaults) in your config. If you fix that it should work.

I'd like consistent maintainers haha, tough balancing this and all the work I have. Where can I recruit them?

**Comment by MuhammadBilal848** [comment]
I tried and it worked (not with together ai but with deepinfra). Thanks 

```
API:
  LARGE_MODEL: meta-llama/Meta-Llama-3-8B-Instruct
  LARGE_API_KEY: CREARE_YOUR_OWN_FREE_API
  LARGE_BASE_URL: https://api.deepinfra.com/v1/openai
  LARGE_MODE: api
  SMALL_MODEL: meta-llama/Meta-Llama-3-8B-Instruct
  SMALL_BASE_URL: https://api.deepinfra.com/v1/openai
  SMALL_API_KEY: CREARE_YOUR_OWN_FREE_API
  SMALL_MODE: api
HUGGINGFACE:
  HUB_PATH: yourusername/your-path-here
  PRIVATE: False
  PUSH_TO_HUB: False
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./input
  OUTPUT: ./output
  PROMPTS: ./prompts
PHASE:
  PHASE_INDEX: 3
  WORK_IN_PHASES: False
SKIP:
  ANSWER_RELEVANCY_CHECK: False
  REPAIR_QA_TUPLES: False
  FILTER_CHUNKS: False
  QUESTION_CHECK: False
  CONVERSATION_GENERATION: False
SYSTEM:
  CHUNK_SIZE: 1900
  COMPLETION_MODE: False
  CONCURRENCY_LIMIT: 50
  CONVERSATION_INSTRUCTIONS: For this conversation, you are generating a chat between
    a generalist, generic AI assistant, and a human.
  DOUBLE_CHECK_COUNTER: 1
  DO_NOT_USE_SYSTEM_PROMPTS: False
  FINAL_ASSISTANT_PROMPTS_NO_RAG: [
  'You are a helpful AI assistant.',
  'You are A VASTLY intelligent ARTIFICIAL INTELLIGENCE with DOMAIN-EXPERT KNOWLEDGE from a variety of fields.
  
  USE your knowledge to be helpful and truthfully answer questions about the world.',
  "u are ai asstant plz answr questions"] # a wide variety of system prompts helps the AI learn better. What, you expect your users to spell things right?
  FINAL_ASSISTANT_PROMPTS_RAG: [
  'You are a helpful AI assistant. Some knowledge:
  
  {data}',
  
  '{data}
  
  You are an AI domain expert. Answer questions',
  'You are an AI with vast knowledge. Here is some potentially-relevant context:
  
  {data}

  Answer questions according to your knowledge.']
  STOP: True
  SUBSET_SIZE: 20
  USE_FILENAMES: False
  USE_SUBSET: True
  RAG_FAILURE_PERCENTAGE: 0.1 # How much of the RAG data has the wrong chunk retrieved deliberately? To train it to answer correctly even if wrong facts are shown to it. We will need another dataset thing for making data where the question asks something that is not present and the rag retrieves something irrelevant obbviously and it is supposed to say "I don't know" or something.
SCRAPING:
  USE_GUTENBERG: False
  START_URL: "https://www.gutenberg.org/ebooks/bookshelf/57"
  MAX_BOOKS: 5
  MAX_FAILURES: 5
```

**Comment by MuhammadBilal848** [comment]
> Check the traceback, you're getting a 401. This seems to be because you have set the api key and model for the large model, but not the small one (which is still using deepinfra defaults) in your config. If you fix that it should work.
> 
> I'd like consistent maintainers haha, tough balancing this and all the work I have. Where can I recruit them?

Just two more questions:

Q1. If I want to change the format of the created dataset to **alpaca** is there any configuration for that?
Q2. I provided in the input folder a pdf of 100 smth pages (all text). while the qna pairs I got were not much as per pdf text.
