### ISSUE TITLE
Request URL has an unsupported protocol 'hhttp://'

### ISSUE THREAD

**Issue by ERmak148** [e-p-armstrong/augmentoolkit#90]
2024-12-27 22:13:03,282 - ERROR - Above prompt resulted in error, probably the model's fault: Connection error.
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/user/.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 171, in handle_async_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL has an unsupported protocol 'hhttp://'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1576, in _request
    response = await self._client.send(
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL has an unsupported protocol 'hhttp://'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/user/.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 171, in handle_async_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL has an unsupported protocol 'hhttp://'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1576, in _request
    response = await self._client.send(
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL has an unsupported protocol 'hhttp://'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/user/.local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 171, in handle_async_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL has an unsupported protocol 'hhttp://'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1576, in _request
    response = await self._client.send(
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_client.py", line 1776, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/user/.local/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL has an unsupported protocol 'hhttp://'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/aug/aug/augmentoolkit/generation_functions/generation_step_class.py", line 142, in generate
    response, timeout = await self.engine_wrapper.submit_chat(
  File "/home/user/aug/aug/augmentoolkit/generation_functions/engine_wrapper_class.py", line 113, in submit_chat
    stream = await self.client.chat.completions.create(
  File "/home/user/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1720, in create
    return await self._post(
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1843, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1537, in request
    return await self._request(
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1600, in _request
    return await self._retry_request(
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1670, in _retry_request
    return await self._request(
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1600, in _request
    return await self._retry_request(
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1670, in _retry_request
    return await self._request(
  File "/home/user/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1610, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
Generation step failed -- too many retries!
Traceback (most recent call last):
  File "/home/user/aug/aug/augmentoolkit/generation_functions/pipeline_step_class.py", line 89, in generate_data
    result, full_output = await generator.generate(**processed_data, **self.static_arguments)
  File "/home/user/aug/aug/augmentoolkit/generation_functions/generation_step_class.py", line 181, in generate
    raise Exception("Generation step failed -- too many retries!")
Exception: Generation step failed -- too many retries!
cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/home/user/aug/aug/augmentoolkit/generation_functions/pipeline_step_class.py", line 133, in run
    result, full_output = await self.generate_data(processed_data, engine_wrapper)
TypeError: cannot unpack non-iterable NoneType object
100%|██████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:08<00:00,  8.20s/it]COMPLETED PHASE 1
Traceback (most recent call last):
  File "/home/user/aug/aug/original/processing.py", line 436, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/aug/aug/original/processing.py", line 317, in main
    print(generated_qa_dicts[0])
IndexError: list index out of range

im using ollama btw

**Comment by KlausikPL** [comment]
Hhtp is not URL
HTTPS or http

**Comment by e-p-armstrong** [comment]
Klausik is correct on this one, that's a typo
